name = "lean-uri"
version = "0.1.0"
defaultTargets = ["LeanUri"]
testDriver = "testURI"

[[lean_lib]]
name = "LeanUri"

[[lean_lib]]
name = "UriTesting"

[[lean_exe]]
name = "testURI"
root = "TestRunner"
